### ISSUE TITLE
at checkExecSyncError (child_process.js:616:11) at execFileSync (child_process.js:634:15)

### ISSUE THREAD

**Issue by zhangxiaofei123** [ericvicenti/react-native-community#46]
BUILD FAILED in 3s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (/Volumes/ZXF/code/zxfProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Volumes/ZXF/code/zxfProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /Volumes/ZXF/code/zxfProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Command.handleAction (/Volumes/ZXF/code/zxfProject/node_modules/react-native/node_modules/@react-native-community/cli/build/cliEntry.js:160:7)

react-native 0.6.05

**Comment by onlineaid** [comment]
I have the same problem.........

(node:5436) UnhandledPromiseRejectionWarning: Error: Command failed: wmic process where (ParentProcessId=14124) get ProcessId 2> nul
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at kill (D:\mern_project_01\node_modules\nodemon\lib\monitor\run.js:345:26)
    at Function.run.kill (D:\mern_project_01\node_modules\nodemon\lib\monitor\run.js:437:7)
    at Bus.<anonymous> (D:\mern_project_01\node_modules\nodemon\lib\monitor\run.js:507:7)
    at Bus.emit (events.js:327:22)
    at restartBus (D:\mern_project_01\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (D:\mern_project_01\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:315:20)
    at FSWatcher.emitWithAll (D:\mern_project_01\node_modules\chokidar\index.js:540:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
